### ISSUE TITLE
Mod Loading Failure (v1.1.1)

### ISSUE THREAD

**Issue by kythorn** [iChun/BetterThanLlamas#1]
Mod Version: 1.1.1
Minecraft version: 1.16.4
Forge Version:  35.1.3

Null Pointer Exception during startup. Crashlog attached.

[crashlog.txt](https://github.com/iChun/BetterThanLlamas/files/5667659/crashlog.txt)

**Comment by rfyuz** [comment]
Occurred to me too, suddenly and without me modifying anything in my installation. Was working previously.

Mod version: 1.1.1
Minecraft version: 1.16.5
Forge version: 36.0.58

Null Pointer Exception occurred during startup at at net.minecraft.entity.LivingEntity.<init>(LivingEntity.java:205). See full stack trace and other information in the crash log attached.
[crash-2021-04-01_12.58.31-fml.txt](https://github.com/iChun/BetterThanLlamas/files/6243050/crash-2021-04-01_12.58.31-fml.txt)
Edit: corrected the Forge version

**Comment by VL4DST3R** [comment]
Same here, same mod and game version

**Comment by iChun** [comment]
Cause of the date I think it's likely due to the easter egg on April 1st and Dec 9. This has been fixed for 1.18 onwards. Unfortunately I no longer support 1.16.5, so I will be marking this as closed. Sorry about that!
