### ISSUE TITLE
Crash on game load?

### ISSUE THREAD

**Issue by itsdinkd** [iChun/BetterThanLlamas#2]
My modpack, AQM3 was working fine yesterday, however, a few people are now encountering a crash where they tried on numerous computers and they are all crashing when their game loads. 

Latest log; https://gist.github.com/TylerPos/67175f22675f641c40c086adce5ebfe5

Crash report; https://paste.corebot.dev/poqenotiye.rb

**Comment by iChun** [comment]
Uhh crap, I think this might be the Easter egg the mod has that's supposed
to trigger today. I don't think there's a config for it so you might have
to either remove the mod for today or change the computer's date.

**Comment by itsdinkd** [comment]
Not as simple to just remove the mod, as it's in my modpack that is on curseforge. To remove it and then add it requires 2 update releases, which takes time. I recommend next time implementing something like this to test it out prior to making it live.

**Comment by iChun** [comment]
Well you see, it worked when I first made it, and definitely worked for a
while. It must have just busted due to one of the ports to a new Minecraft
version.

**Comment by iChun** [comment]
I'll fix this eventually should you leave the issue open. As a workaround you can tell people experiencing the crash to just remove the mod locally on their end or change their system clock, or just wait till its no longer April 1st.
