### ISSUE TITLE
Mod somehow down or making problems.

### ISSUE THREAD

**Issue by Adrian157157** [iChun/BetterThanLlamas#5]
For a few hours there have been many people (including me) reporting issues with this mod.

There is a popular modpack called Stoneblock 3 that uses this mod.
Since a few hours the modpack can no longer be loaded because of the following:

net.minecraftforge.fml.ModLoadingException: Better Than Llamas (betterthanllamas) encountered an error during the done event phase
§7java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.Level.m_46658_()" because "p_21369_" is null

Until now nobody knows how to fix this problem so I thought contacting the creator might be a good idea.

**Comment by Espergium** [comment]
https://github.com/iChun/BetterThanLlamas/issues/3#issue-1485635718

See the issue that was filed a day ago here.

**Comment by iChun** [comment]
An update for 1.18 has been released to address this issue, sorry bout the crashes! I fixed this for 1.19 but didn't realise people would stick to 1.18 for the moment.

Sunekaer has been informed as well.
