### ISSUE TITLE
Game not loading

### ISSUE THREAD

**Issue by AFamiliarity** [iChun/BetterThanLlamas#6]
Game does not load in my modpack
https://mclo.gs/8aEolPn
[filelist.txt](https://github.com/iChun/BetterThanLlamas/files/14230888/filelist.txt)

**Comment by iChun** [comment]
![image](https://github.com/iChun/BetterThanLlamas/assets/2298444/acbc5722-fb9b-43ac-a967-86b2b70ca94c)
