### ISSUE TITLE
Malformed `pack.mcmeta`

### ISSUE THREAD

**Issue by YoshiRulz** [iChun/BetterThanLlamas#7]
It looks like https://github.com/iChun/BetterThanLlamas/commit/a16670ce18fb1b86f0561c345e77a55c9db405fb intended to make this a template populated at build-time, but at least the Fabric build scripts don't fill it in correctly. From [this artifact](https://modrinth.com/mod/better-than-llamas/version/96ivnRJF):
```json
{
   "pack": {
      "description": {
         "text": "${mod_name}"
      },
      "pack_format": ${minecraft_pack_format}
   }
}
```
This prevents some (all?) of the textures from loading.

[The previous version](https://modrinth.com/mod/better-than-llamas/version/VU7I8OjW) works fine in 1.20.4.

**Comment by iChun** [comment]
An oversight on my part, I found it out the hard way as well during development. Will fix
