### ISSUE TITLE
Crash on world Load Due to [Resource Key?]

### ISSUE THREAD

**Issue by RyanC-1229** [iChun/BetterThanLlamas#9]
This might not be an issue with these mods but removing them allowed me to enter the world so wanted to share just in case
Mods:
IchunUtil
Better Than Rabbits
Better Than Llamas
MC Version: 1.21
Modloader: NeoForge 21.0.57
https://pastebin.com/87DDRKFG

**Comment by UnRealDinnerbone** [comment]
This is an issue with JAMD version 5.0.2 should fix this, or at least stop the game from crashing

**Comment by RyanC-1229** [comment]
Welp I tried 
Sorry about that 
Thank you!
